my_lst = [1,2,4,4,87,24,65,5,67,8]
print("print original list:", my_lst)
my_copy_lst = my_lst.copy()
print("print copied list:", my_copy_lst)
my_lst.clear()
print("print original list after clear:", my_lst)
my_lst.append(45)
my_copy_lst.append(23)
print("print append copy list:", my_copy_lst)
my_copy_lst.pop()
print("print pop copy list:", my_copy_lst)
my_lst.remove(45)
my_copy_lst.remove(4)
print("print removed element copy list:", my_copy_lst)
my_copy_lst.sort()
print("print sort copy list:", my_copy_lst)
my_copy_lst.reverse()
print("print reverse copy list:", my_copy_lst)
my_lst.extend([188,6,45])
print("print original list:", my_lst)
my_copy_lst.extend([102,200])
print("print extended copy list:", my_copy_lst)
my_copy_lst.insert(1,89)
print("print item inserted copy list:", my_copy_lst)
print("length of the list", len(my_copy_lst))

