file = open('resource.txt', "r")
print(file.read())
print("-----------")
#file.close()
file = open("resource.txt", "w")
file.write("\ngod bless him")
#file.close()
file = open("resource.txt", "a")
file.write("\nbut has many impediments")
#print(file.read())
file.close()
